# <meta name="theme-color" content="this">
meta_theme_color: red

# path to favicon
favicon: ""

# path to highlight.js theme
# http://jmblog.github.io/color-themes-for-highlightjs
hljs_theme: "tomorrow-night.css"